using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using WorkWave.PestPac.TA.Configuration;
using WorkWave.TA.TestEngine;
using WorkWave.PestPac.TA.Model;

namespace WorkWave.PestPac.TA
{
    class PestPacSupport
    {
        private static PestPacConfiguration pestPacConfig;

        public static void InitializePestPacConfig()
        {
            string workingDir = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
            string configFile_FullName = String.Format("{0}\\PestPacConfig.json", workingDir);

            try
            {
                using (StreamReader file = new StreamReader(configFile_FullName))
                {
                    string json = file.ReadToEnd();
                    pestPacConfig = JsonConvert.DeserializeObject<PestPacConfiguration>(json);
                }
            }
            catch (FileNotFoundException)
            {
                string errMsg = String.Format("Could not find the PestPacConfig file, {0}.  This file is purposedly ommitted from source control to protect the integrity " +
                    "of the test database running in the continuous delivery pipeline.  It will be automatically generated by the " +
                    "CI server in the pipeline (database creds stored in secure variables).  Developers, to run this locally, " +
                    "generate a PestPacConfig.json file (rpierro@workwave.com for template) and place in the Configuration folder.", configFile_FullName);

                SUT.Log.Fatal(errMsg);

                throw;
            }
        }

        public static string DefaultLocation
        {
            get { return pestPacConfig.Default_Location; }
        }

        public static string DefaultCompanyKey
        {
            get { return pestPacConfig.Default_CompanyKey; }
        }

        public static string DefaultUsername
        {
            get { return pestPacConfig.Default_Username; }
        }

        public static string DefaultPassword
        {
            get { return pestPacConfig.Default_Password; }
        }
 
      
    }
}
