using System;
using System.IO;
using Newtonsoft.Json;
using WorkWave.PestPac.TA.Configuration;
using WorkWave.TA.TestEngine;

namespace WorkWave.PestPac.TA
{
    class SalesCenterSupport
    {
        private static SalesCenterConfiguration pestPacConfig;

        public static void InitializePestPacConfig()
        {
            var workingDir =
                System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
            var configFile_FullName = string.Format($"{workingDir}{Path.DirectorySeparatorChar}SalesCenterConfig.json");

            try
            {
                using (var file = new StreamReader(configFile_FullName))
                {
                    var json = file.ReadToEnd();
                    pestPacConfig = JsonConvert.DeserializeObject<SalesCenterConfiguration>(json);
                }
            }
            catch (FileNotFoundException)
            {
                var errMsg = string.Format(
                    "Could not find the PestPacConfig file, {0}.  This file is purposedly ommitted from source control to protect the integrity " +
                    "of the test database running in the continuous delivery pipeline.  It will be automatically generated by the " +
                    "CI server in the pipeline (database creds stored in secure variables).  Developers, to run this locally, " +
                    "generate a PestPacConfig.json file (rpierro@workwave.com for template) and place in the Configuration folder.",
                    configFile_FullName);

                SUT.Log.Fatal(errMsg);

                throw;
            }
        }

        public static string DefaultLocation => pestPacConfig.Default_Location;

        public static string DefaultCompanyKey => pestPacConfig.Default_CompanyKey;

        public static string DefaultUsername => pestPacConfig.Default_Username;

        public static string DefaultPassword => pestPacConfig.Default_Password;
    }
}